dist: xenial
language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
install:
  - pip install -q $DJANGO
  - pip install tablib==0.12.1
  - pip install -r requirements/base.txt
  - pip install coveralls
script:
   - python -Wall -m coverage run --omit='setup.py' --source=. tests/manage.py test core --settings=
after_success:
  - coveralls
matrix:
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
